const express = require('express')
const app = express()
const helmet = require('helmet')
const cors = require('cors')
const morgan = require('morgan')
const bodyParser = require('body-parser')
const orderRoutes = require('./routes/orders')
const lineRoutes = require('./routes/lines')
const operationRoutes = require('./routes/operations')
const PORT = process.env.PORT || 3000

app.use(cors())
app.use(helmet())
app.use(morgan('tiny'))
app.use(bodyParser.urlencoded({ extended: true }))
app.use(bodyParser.json())

app.get('/orders', orderRoutes.getOrders)
app.get('/lines', lineRoutes.getLines)
app.get('/findByNumber/:orderNumber', orderRoutes.findByNumber)
app.get('/findLines/:orderNumber', lineRoutes.findLine)
app.get('/findByName/:name', orderRoutes.findByName)
app.post('/orders', orderRoutes.postOrder)
app.post('/lines', lineRoutes.postLine)
app.put('/updateOrder/:orderNumber', orderRoutes.updateOrder)
app.put('/updateLine/:orderNumber', lineRoutes.updateLine)

app.listen(PORT)
